### PR TITLE
Guess wmst timeframes

### PR DESCRIPTION
**Pull request by rduivenvoorde**
Having a Geoserver with WMS-t layers, adding a layer via TimeManager is really difficult.
Guessing the time formats etc etc is just hard (besides the most often used timeformat was not yet part of the predefined formats :-) ) 

So this commits use urllib to request the (version 1.3.0-) capabilities of the wms-t layer, tries to get the 'Dimension' node and then tries to interpret the value of it.

There are a lot of different ways to define those ranges, but most wms's use a notation like 
``2018-09-25T13:10:00.000Z/2018-09-26T01:00:00.000Z/PT10M``
being start/time/period

Unfortunately we cannot use the Period-definition yet, PT10M for example could be used to so set timeFrameSize 10 and timeFrameType to minutes...

Some public service to try:
Dutch rain-radar (epsg:28992):
``http://geoservices.knmi.nl/cgi-bin/RADNL_OPER_R___25PCPRR_L3.cgi``
Nasa (with SOME layers time enabled).
``https://neo.sci.gsfc.nasa.gov/wms/wms``

For the dutch service requesting a layer using TIME=start/end format returns a stack of images from start to end, so it's better to request it using TIME=moment or TIME=moment/moment
This is made possible to bring back(?) the zero sized timeframe. Defining a zero-timeframe the wms-t request will have TIME=moment/moment formats. 
To make it possible to step through time (eg using the forward/backward buttons) with a zero-timeFrameSize I look at the current timeFrameType dropdown. So having a timeFrameSize of 0 and a timeFrameType of day, you wil step day by day. When having a non-zero timeFrameSize old behaviour should not have been changed.

Not sure if I should make this a WIP (Work In Progress) or not.
Would be nice if people could test some of their services (it works for my own Geoserver and above services).

Another thing that would be nice, is to have more feedback when a user tries to add a layer, adding a wms-t layer will silently fail, without any suggestion what is wrong (timeformat or other)?
Should we make it possible to the MessageLog or to the MessageBar?

Then there is the 'problem' that I just used the start that was already there which used urllib, instead of the better QgsNetworkAccessManager...

I hope people have some services to test.

### CODE REVIEW

**Comment by anitagraser** [comment]
Awesome! I'll try it with my GeoServer. I've never before seen the period in start/time/period. Is that GeoServer default?

**Comment by rduivenvoorde** [comment]
@anitagraser No, that is OGC notation, and the period is an ISO standard notation. The example url's are two different (not geoserver) examples and have the same start/end/period Dimension. But there are A LOT of different notations.

See https://github.com/rduivenvoorde/TimeManager/blob/guess_wmst_timeframes/raster/wmstlayer.py#L53

Geoserver has 3 ways to show it: as 'List', as 'Interval and Resolution' and as 'Continues Interval'

With me, pointing to a Geoserver wms-t layer which as either List or Interval and Resolution, just works. That is no need to fill in any cell of a row in the 'add layer' dialog. Just click OK

**Comment by rduivenvoorde** [comment]
About my TODO: get rid of urllib in favor of QgsNetworkAccessManager: would be nice to use:
https://qgis.org/api/classQgsNetworkAccessManager.html#a0e279eac4a65ca769575fce76ef5c5be
But that is only available QGIS >= 3.6 ... 
I will also test if current urllib lines work behind a proxy

**Comment by anitagraser** [comment]
> Geoserver has 3 ways to show it: as 'List', as 'Interval and Resolution' and as 'Continues Interval'
> With me, pointing to a Geoserver wms-t layer which as either List or Interval and Resolution, just works. That is no need to fill in any cell of a row in the 'add layer' dialog. Just click OK

Ok, my WMS-T is 'continuous interval' if I remember correctly. Hopefully I'll get around to testing it tomorrow

**Comment by anitagraser** [comment]
Sorry I haven't gotten around to testing this yet.

**Comment by rduivenvoorde** [comment]
ping @anitagraser 
Can you please have a look at this? I think it is really helpfull for people using Dimensions in WMS servers. It works (for me) both in Geoserver and Minnesota Mapserver for most common DateTime formats (like ISO ones)

**Comment by anitagraser** [comment]
Hi @rduivenvoorde 
I tried to add my GeoServer WMST but it seems to have silently failed. Trying to reopen the settings, I get 

```
2019-11-22T15:05:38     WARNING    Traceback (most recent call last):
              File "C:/Users/agraser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\timemanagercontrol.py", line 271, in showOptionsDialog
              self.loopAnimation)
              File "C:/Users/agraser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\timemanagerguicontrol.py", line 394, in showOptionsDialog
              settings = layer_settings.getSettingsFromLayer(layer)
              File "C:/Users/agraser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\layers\layer_settings.py", line 176, in getSettingsFromLayer
              result.timeFormat = layer.getTimeFormat()
              File "C:/Users/agraser/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\layers\timerasterlayer.py", line 51, in getTimeFormat
              return self.timeFormat
             AttributeError: 'WMSTRasterLayer' object has no attribute 'timeFormat'
```

**Comment by anitagraser** [comment]
I went back to check with TimeManager 3.4 and that does work for me. The format my server is usding is 2014-01-01T00:00:00Z

**Comment by rduivenvoorde** [comment]
@anitagraser I will check with current master version too, maybe more things have changed....
Do you have a public geoserver?

Another thing I see:
```
class WMSTRasterLayer(TimeRasterLayer):
    IGNORE_PREFIX = "IgnoreGetFeatureInfoUrl=1&IgnoreGetMapUrl=1&"

    def __init__(self, settings, iface=None):
        TimeLayer.__init__(self, settings.layer, settings.isEnabled)
```
WMSTRasterLayer has a WMSTRasterLayer as parent, but is calling TimeLayer.__init__ constructor (so the parent class of WMSTRasterLayer)... And TimeLayer does not have a 'timeformat' property

Can you check if you do 
`WMSTRasterLayer.__init__(self, settings.layer, settings.isEnabled)`
instead of
`TimeLayer.__init__(self, settings.layer, settings.isEnabled)`
in the constructor?

**Comment by anitagraser** [comment]
Unfortunately, it's not public and I cannot access it from outside the office.

**Comment by anitagraser** [comment]
If I change the constructor, I get the following error when adding the layer:

```
An error occurred while trying to add layer <layername> to TimeManager. Cause: 'QgsRasterLayer' object has no attribute 'layer'
```

**Comment by rduivenvoorde** [comment]
Ok, strange. I'm already on Master, and this is working fine for me (without the thing I just mentioned).
Anyway, in the code are some public services to test:

Dutch rain-radar (epsg:28992):
http://geoservices.knmi.nl/cgi-bin/RADNL_OPER_R___25PCPRR_L3.cgi

Nasa (with SOME layers time enabled).
https://neo.sci.gsfc.nasa.gov/wms/wms

And besides those, there is a  service in https://github.com/anitagraser/TimeManager/issues/308 you can use:  https://maps.dwd.de/geoserver/dwd/wms?  
then layer: Fachlayer/Wetter/Radar/SF-Produkt/sf-produkt

**Comment by anitagraser** [comment]
Development of TimeManager has stopped. I'm therefore closing remaining PRs.

**Pull request closed without merging**
