### PR TITLE
Travisfix

### PR DESCRIPTION
**Pull request by carolinux**

### CODE REVIEW

**Comment by carolinux** [comment]
seems like postgis is missing now from travis builds, not sure why, need to investigate

**Comment by carolinux** [comment]
https://docs.travis-ci.com/user/database-setup/#Using-PostGIS

**Comment by rduivenvoorde** [comment]
This error "$libdir/postgis-2.2" looks like there are conflicting version of postgis/postgres?

The earlier change: "sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list" does that not remove the postgis ppa? Is that this one: https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa
Because that one shows only postgis 2.1 ?
We are installing postgres 9.3? Maybe downgrade that one?

**Comment by carolinux** [comment]
it says in the travis docs 'All installed versions of PostgreSQL include PostGIS 2.1 .'
but then my create extension command fails because postgis 2.2 wasn't found... -_-

**Comment by carolinux** [comment]
also the original problem (leading me to comment out this line) was that the ubuntu-gis-sources.list file suddenly did not exist, after travis working for years without issue.

**Comment by carolinux** [comment]
I asked my :8ball: and found the solution

**Pull request merged**
