### PR TITLE
Remove netcdftime dependency

### LINKED ISSUE #320: netCDF4 library support
I have installed the TimeManager plugin (v3.4) and the netCDF4 library is correctly installed by using "pip install netCDF4" in Python3. The library is successfully loaded and used by other QGIS3 plugins (i.e. 'Spectral/temporal profile tool'). However, when selecting a raster in TimeManager settings and checking the option "layer is netCDF file with time dimension", I keep visualizing the following error message: "for full CDF support please pip install netCDF4".
Any ideas to solve this problem?

### PR DESCRIPTION
**Pull request by radosuav**
Fixes #320

### CODE REVIEW

**Comment by anitagraser** [comment]
Please ensure that the PR does not cause test failures.

**Comment by radosuav** [comment]
I pushed a fix but it did not seem to trigger tests.

**Comment by radosuav** [comment]
Now all the tests are passing but please note that that the main change in this PR is not covered by tests. However, I tested it manually in QGIS.

**Comment by DerLude** [comment]
In QGIS 3.14 and 3.10 as well, I received an message "For full CDF support please pip install netCDF4" when I tried to load the time dimension of a netCDF. It seems that the problem was a result of the removal of the netcdftime dependency. I had already installed "netCDF4" (as the message implied), but not "netcdftime", which is checked by haveNetCDF() in rasterdialog.py as well.
After 'pip install netcdftime', everything worked again in QGIS 3.10. However, after upgrading to QGIS 3.14 again (and upgrading to TimeManager 3.5 as well), the QGIS Plugin Manager tells me that Time Manager is incompatible with QGIS>3.12.

**Comment by anitagraser** [comment]
Development of TimeManager has stopped. I'm therefore closing remaining PRs.

**Pull request closed without merging**
