### PR TITLE
Time Improvements, Signal handling refactoring, Tests

### PR DESCRIPTION
**Pull request by carolinux**
I realized I was doing some things inefficiently in my previous pull request #76
This will be a PR to clean up and see if I can further organize/abstract the time related functionality. Please don't merge yet. :) Will also fix issues reported in #26 with the goal to make time from year 0 to year +reasonably in the future+ usable.

Note: Time refactoring also grew into refactoring some of the signal handling and adding some tests for stability.

### CODE REVIEW

**Comment by carolinux** [comment]
Only thing left now is to see that this works for sure on Windows

**Comment by anitagraser** [comment]
Thanks for the update! Looking forward to giving it a test run and then it's time to release an update I think :-)

**Comment by carolinux** [comment]
Alright @anitagraser, you can give it a test run. With a few changes it worked on Windows too. One was to take care of filenames for the frames (because windows is more strict) and the other was a portability issue to my strftime hack

**Comment by carolinux** [comment]
I wonder, what platform are the majority of the users using? I don't have easy access to test things out in a MacBook at the moment.

**Comment by anitagraser** [comment]
I don't have a Mac either, so we'll probably have to wait for somebody offering to test on Mac. (Guessing from gis.stackexchange questions, Windows and Ubuntu are more common.)

**Comment by carolinux** [comment]
Alright. I will try setting up a hackintosh on my ubuntu in the meantime to test.

**Comment by carolinux** [comment]
@anitagraser I tested it on Mavericks. No problems. Let's merge this. :)

**Comment by anitagraser** [comment]
Thanks a lot! I'll prepare the new plugin version release.

**Comment by anitagraser** [comment]
The sqlite test data uses timestamps with "T" instead of space (like https://github.com/anitagraser/TimeManager/issues/83) but that format doesn't seem supported yet. Is that correct?

**Comment by carolinux** [comment]
Hm, I haven't loaded T timestamps into the sqlite db. If you load the test data from sqlite it will work. The format is time_util.DEFAULT_FORMAT.

**Comment by carolinux** [comment]
ah ok, I see why. In the binary .sqlite file it does have this T separator in dates. weird, but it may just be how the thing looks in binary. The actual dates are in regular YMD HMS.

**Comment by anitagraser** [comment]
Oh, I guess I must have loaded the layer using OGR ...

**Pull request merged**
