### PR TITLE
Time manager returns to life again after temporal controller

### PR DESCRIPTION
**Pull request by javadadabi**
Hi 
Dear Anita
Thank you for your response.
As you mentioned, I fork TimeManager repository and continued the plugin development.
And now it's the time to compare and accept my pull request
Best regards,
Seyed Javad

### CODE REVIEW

**Comment by anitagraser** [comment]
Dear Seyed Javad,

There is no need for a pull request. I don't have the resources to get back to maintaining this plugin. Therefore I recommend you continue to work on your fork and we update the plugin meta data to point to your repository (including bug tracker).

Regards,
Anita

**Comment by javadadabi** [comment]
Dear Anita
As you mentioned:"The project has reached a stable, usable state but the
author(s) have ceased all work on it. A new maintainer may be desired."
I am volunteer to maintain TimeManager plugin.
I will push changes again but now in my fork. Is it possible to give me a
some authorities to continue The plugin maintainance and developement?
Best Regards
Seyed Javad

در تاریخ چهارشنبه ۸ دسامبر ۲۰۲۱،‏ ۱۵:۲۸ Anita Graser <
***@***.***> نوشت:

**Comment by anitagraser** [comment]
I've added your account to the list of owners in https://plugins.qgis.org/plugins/timemanager/

That should enable you to upload new versions. 

image


Please enable issue tracking on https://github.com/javadadabi/TimeManager

Then we should also update the plugin repository and tracker URLs.

**Comment by javadadabi** [comment]
Thank you for adding my account to the owners list.
Issues was enabled for TimeManager repository.

در تاریخ چهارشنبه ۸ دسامبر ۲۰۲۱،‏ ۱۶:۵۸ Anita Graser <
***@***.***> نوشت:

**Comment by anitagraser** [comment]
Great, I think most of the information on the plugin platform page will be updated automatically from the metadata (https://github.com/javadadabi/TimeManager/blob/master/metadata.txt) once you upload a new version of the plugin.

**Comment by javadadabi** [comment]
Hi
Dear Anita
I pushed changes to my fork in github repository and a new version was
uploaded to qgis plugins repository but it is not approved yet.
So, please check uploded plugin and approve timemanager version 3.6.
Best regards
Seyed Javad

در تاریخ چهارشنبه ۸ دسامبر ۲۰۲۱،‏ ۱۷:۵۸ Anita Graser <
***@***.***> نوشت:

**Pull request closed without merging**
