### PR TITLE
possible fix for #188, also implements #167?

### PR DESCRIPTION
**Pull request by rduivenvoorde**
see #188 and #167 

this seams an easy fix, but not sure if there are any other reasons to not do it like this.

### CODE REVIEW

**Comment by carolinux** [comment]
Something must have changed with travis lately

**Comment by carolinux** [comment]
@anitagraser any reason not to do it like this?
@rduivenvoorde I suppose you tried it and it works?
I am pretty sure the qtimer error has to do with the timer object disappearing in C++ and then Python being confused, so this PR would fix #167 as well.
I would like to merge it, and fix travis later.

**Comment by rduivenvoorde** [comment]
@carolinux any idea what is exactly the travis problem? I tried to update postgresql (in travis.yaml), but that did not fix it. Maybe use a newer (debian/ubuntu?) image for it?
I'm not a travis guru, so just guessing. But it would be good if travis is wel again :-)
Otherwise we could try to ask one of the qgis-devs to check the error/yaml?

**Comment by carolinux** [comment]
look at #190 (and let's discuss there) - maybe postgis needs to be manually installed.

**Comment by carolinux** [comment]
@rduivenvoorde fixed travis! please merge master in this branch and push againe

**Comment by anitagraser** [comment]
Thanks for looking into this @rduivenvoorde! Time to release a new version? The latest one on plugins.qgis.org is from April 20, 2016

**Comment by carolinux** [comment]
@anitagraser Sure! Maybe you can do it this time? We could up it to 2.5

**Comment by anitagraser** [comment]
@carolinux ok, will do

**Comment by anitagraser** [comment]
Great Github Desktop merged some old stuff in and now I'm struggling to revert ...

**Pull request merged**
