### PR TITLE
Add to README.md

### PR DESCRIPTION
**Pull request by patagonian**
I added some comments about making videos from individual frames using ffmpeg -- perhaps too detailed for the README file?-- but I found that step difficult myself and thought that some explanation might help others.

### CODE REVIEW

**Comment by patagonian** [comment]
Hi Anita,

 

I contacted you long ago about TimeManager and contributed a little bit to the documentation about making videos (although I have fallen off the end of the contributor list because it was so long ago, I think).  In any case, I’m interested in using TimeManager again, and this time I am wondering about whether you have any experience using it for a stack of rasters.  I’m not even exactly sure how that stack would be represented in QGIS, but the idea I’m interested in is showing rainfall patterns on top of an animal track (I figured out how to animate that last time we communicated) and I have long sequences of daily rain and snow rasters in which each layer is a different day.  It would be really neat if it were possible to overlay those changing weather patterns with an animal track, and basically what I would like to do is to turn the layers on one at a time (and then back off) as you step through days.

 

Thanks!  I know you’re busy and I am, as always, very impressed by your output.

 

Best,

 

John

**Comment by carolinux** [comment]
oh I see what you mean.  Have you checked out crayfish? I think they work
with rasters more extensively, but I haven't checked it out myself.
Using Time Manager:
 It would be perhaps easier to add each raster layer (with the add raster)
and specify the endtime/starttime. It would take a while to add manually,
but I can help you script it if you share some data.

**Comment by carolinux** [comment]
But also @patagonian please create a new issue

**Comment by patagonian** [comment]
Hi Karolina,

Thanks so much for the very quick answer.  Crayfish looks really cool – thanks for pointing that out!  The problem is that I want to make an animated map where both raster and vector data change with time.  I could send you a few layers to play with – they’re not very big.  The problem is that with 3 years of daily data, I have about 1,000 raster layers, which is too many to do by hand.  Are you talking about using Python to script the process of importing layers?  I think that since there are so many of them, I might want to leave them in an external file and load them one at a time, then discard each one after it has been used.  It doesn’t matter to me if the process runs fairly slowly, because I’ll be turning the output into a video anyway.

 

Anyway, I’ll add a new issue.

 

Cheers,

 

John

**Comment by patagonian** [comment]
I meant to add that I was looking at Anita’s blog and I saw the entry titled “Using TimeManager for WMS-T layers”.  It looks great, and I am guessing that it has most of the required functionality but perhaps it only loads one layer at a time?

 

John

**Pull request merged**
